source 'https://rubygems.org'
ruby '2.1.2'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib', github: 'maccman/sinatra-contrib'
gem 'thin'
gem 'erubis'
gem 'i18n'
gem 'activesupport'
gem 'rake'
gem 'builder'
gem 'json', '~> 1.7.7'
gem 'dotenv'
gem 'mail'
gem 'email_reply_parser'
gem 'dedent'

# DB
gem 'sequel'
gem 'sinatra-sequel'
gem 'pg'